files:
  use-underscore: true # for Rust filename/code import consistency
  use-hyphen: false
  use-capital: false
  use-pascal-case: false
  use-camel-case: false
  use-screaming-snake-case: false
  allow-unicode: false
  min-length: 3
  max-length: 50

directories:
  use-underscore: true # for Rust filename/code import consistency
  use-hyphen: false
  use-capital: false
  use-pascal-case: false
  use-camel-case: false
  use-screaming-snake-case: false
  allow-unicode: false

empty-files:
  allow-empty: false

duplicate-files:
  allow-duplicates: false

exclude-patterns:
  # - ".git/"
  - "target/"
  - ".env*"
  - "assets/favicon.svg"
